language: dart
dart:
  - 1.23.0
with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
