name: route_hierarchical
version: 0.10.4
description: A client routing library for Dart
authors:
  - Justin Fagnani <justinfagnani@google.com>
  - Pavel Jbanov <pavelj@google.com>
homepage: https://github.com/angular/route.dart

environment:
  sdk: '>=1.9.0 <3.0.0'

web:
  compiler:
    debug: dartdevc

dependencies:
  logging: ">=0.11.3 <1.0.0"
  uuid: ^1.0.0

dev_dependencies:
  analyzer: ">=0.27.3 <2.0.0"
  build_runner: ">=0.6.0 <1.0.0"
  build_test: ">=0.9.0 <1.0.0"
  build_web_compilers: ">=0.2.0 <1.0.0"
  coverage: ">=0.7.2 <2.0.0"
  dart_dev: ^1.9.4
  dart_style: ">=0.2.1 <2.0.0"
  mockito: ">=0.10.0 <2.0.0"
  test: ">=0.12.3+5 <2.0.0"

transformers:
  - test/pub_serve:
      $include: test/**_test{s*,}{.*,}.dart
